<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/01/25 10:39:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=checck;host=localhost',
  'username' => 'root',
  'password' => '',
  'attributes' => 
  array (
    'quote_identifier' => true,
  ),
  'name' => 'doctrine',
)),);
