<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/03/28 09:37:46
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
