<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/01/25 04:44:32
sfConfig::add(array(
  'mod_projectscomments_enabled' => true,
  'mod_projectscomments_view_class' => 'sfPHP',
));
