<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/01/29 00:27:29
sfConfig::add(array(
  'mod_projectsreports_enabled' => true,
  'mod_projectsreports_view_class' => 'sfPHP',
));
